FROM alpine:3.15
MAINTAINER Hofstadter, Inc <open-source@hofstadter.io>

RUN apk add --no-cache --virtual .build-deps \
		ca-certificates \
		git \
		&& \
    apk del .build-deps && \
    rm -rf /root/.cache

COPY hof /usr/local/bin/hof
ENTRYPOINT ["hof"]

VOLUME ["/work"]
WORKDIR /work
