FROM debian:11.3
MAINTAINER Hofstadter, Inc <open-source@hofstadter.io>

RUN apt-get update -y \
	&& apt-get install -y \
		ca-certificates \
		git \
	&& apt-get clean \
	&& apt-get autoremove --yes \
  && rm -rf /var/lib/{apt,dpkg,cache,log}/

COPY hof /usr/local/bin/hof
ENTRYPOINT ["hof"]

VOLUME ["/work"]
WORKDIR /work
