// Code generated by pigeon; DO NOT EDIT.

// Package 'parser' implements the basic parser for 'hof-lang'
package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/hofstadter-io/hof/pkg/ast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "HOF",
			pos:  position{line: 6, col: 1, offset: 83},
			expr: &actionExpr{
				pos: position{line: 6, col: 8, offset: 90},
				run: (*parser).callonHOF1,
				expr: &seqExpr{
					pos: position{line: 6, col: 8, offset: 90},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 6, col: 8, offset: 90},
							label: "pkg",
							expr: &ruleRefExpr{
								pos:  position{line: 6, col: 12, offset: 94},
								name: "PackageDecl",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 6, col: 24, offset: 106},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 6, col: 27, offset: 109},
							label: "imports",
							expr: &zeroOrOneExpr{
								pos: position{line: 6, col: 35, offset: 117},
								expr: &ruleRefExpr{
									pos:  position{line: 6, col: 35, offset: 117},
									name: "Imports",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 6, col: 44, offset: 126},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 6, col: 47, offset: 129},
							label: "defs",
							expr: &zeroOrOneExpr{
								pos: position{line: 6, col: 52, offset: 134},
								expr: &ruleRefExpr{
									pos:  position{line: 6, col: 52, offset: 134},
									name: "Definitions",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 6, col: 65, offset: 147},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "PackageDecl",
			pos:  position{line: 10, col: 1, offset: 201},
			expr: &actionExpr{
				pos: position{line: 10, col: 16, offset: 216},
				run: (*parser).callonPackageDecl1,
				expr: &seqExpr{
					pos: position{line: 10, col: 16, offset: 216},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 10, col: 16, offset: 216},
							name: "__",
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 19, offset: 219},
							name: "PACKAGE",
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 27, offset: 227},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 10, col: 29, offset: 229},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 10, col: 34, offset: 234},
								name: "NAME",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 10, col: 39, offset: 239},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Imports",
			pos:  position{line: 14, col: 1, offset: 285},
			expr: &actionExpr{
				pos: position{line: 14, col: 12, offset: 296},
				run: (*parser).callonImports1,
				expr: &seqExpr{
					pos: position{line: 14, col: 12, offset: 296},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 14, col: 12, offset: 296},
							name: "IMPORT",
						},
						&ruleRefExpr{
							pos:  position{line: 14, col: 19, offset: 303},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 14, col: 21, offset: 305},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 14, col: 25, offset: 309},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 14, col: 28, offset: 312},
							label: "imports",
							expr: &zeroOrMoreExpr{
								pos: position{line: 14, col: 36, offset: 320},
								expr: &ruleRefExpr{
									pos:  position{line: 14, col: 38, offset: 322},
									name: "Import",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 14, col: 48, offset: 332},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 14, col: 51, offset: 335},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 14, col: 55, offset: 339},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Import",
			pos:  position{line: 18, col: 1, offset: 384},
			expr: &actionExpr{
				pos: position{line: 18, col: 11, offset: 394},
				run: (*parser).callonImport1,
				expr: &seqExpr{
					pos: position{line: 18, col: 11, offset: 394},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 18, col: 11, offset: 394},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 18, col: 14, offset: 397},
							label: "name",
							expr: &zeroOrOneExpr{
								pos: position{line: 18, col: 19, offset: 402},
								expr: &ruleRefExpr{
									pos:  position{line: 18, col: 19, offset: 402},
									name: "ID",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 18, col: 23, offset: 406},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 18, col: 25, offset: 408},
							label: "path",
							expr: &ruleRefExpr{
								pos:  position{line: 18, col: 30, offset: 413},
								name: "String",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 18, col: 37, offset: 420},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Definitions",
			pos:  position{line: 22, col: 1, offset: 467},
			expr: &actionExpr{
				pos: position{line: 22, col: 16, offset: 482},
				run: (*parser).callonDefinitions1,
				expr: &seqExpr{
					pos: position{line: 22, col: 16, offset: 482},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 22, col: 16, offset: 482},
							label: "defs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 22, col: 21, offset: 487},
								expr: &ruleRefExpr{
									pos:  position{line: 22, col: 23, offset: 489},
									name: "Definition",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 22, col: 37, offset: 503},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Definition",
			pos:  position{line: 26, col: 1, offset: 549},
			expr: &actionExpr{
				pos: position{line: 26, col: 15, offset: 563},
				run: (*parser).callonDefinition1,
				expr: &seqExpr{
					pos: position{line: 26, col: 15, offset: 563},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 26, col: 15, offset: 563},
							name: "__",
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 18, offset: 566},
							name: "DEF",
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 22, offset: 570},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 26, col: 24, offset: 572},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 26, col: 29, offset: 577},
								name: "ID",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 32, offset: 580},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 26, col: 34, offset: 582},
							label: "path",
							expr: &ruleRefExpr{
								pos:  position{line: 26, col: 39, offset: 587},
								name: "PATH",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 44, offset: 592},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 26, col: 46, offset: 594},
							label: "body",
							expr: &ruleRefExpr{
								pos:  position{line: 26, col: 51, offset: 599},
								name: "DefnBody",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 26, col: 60, offset: 608},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "DefnBody",
			pos:  position{line: 30, col: 1, offset: 665},
			expr: &actionExpr{
				pos: position{line: 30, col: 13, offset: 677},
				run: (*parser).callonDefnBody1,
				expr: &seqExpr{
					pos: position{line: 30, col: 13, offset: 677},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 30, col: 13, offset: 677},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 17, offset: 681},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 30, col: 20, offset: 684},
							label: "defs",
							expr: &zeroOrMoreExpr{
								pos: position{line: 30, col: 25, offset: 689},
								expr: &ruleRefExpr{
									pos:  position{line: 30, col: 27, offset: 691},
									name: "DefnField",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 40, offset: 704},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 30, col: 43, offset: 707},
							val:        "}",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 30, col: 47, offset: 711},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "DefnField",
			pos:  position{line: 34, col: 1, offset: 760},
			expr: &actionExpr{
				pos: position{line: 34, col: 14, offset: 773},
				run: (*parser).callonDefnField1,
				expr: &seqExpr{
					pos: position{line: 34, col: 14, offset: 773},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 34, col: 14, offset: 773},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 34, col: 17, offset: 776},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 34, col: 23, offset: 782},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 34, col: 23, offset: 782},
										name: "TypeDecl",
									},
									&ruleRefExpr{
										pos:  position{line: 34, col: 34, offset: 793},
										name: "Field",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 42, offset: 801},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "TypeDecl",
			pos:  position{line: 38, col: 1, offset: 827},
			expr: &actionExpr{
				pos: position{line: 38, col: 13, offset: 839},
				run: (*parser).callonTypeDecl1,
				expr: &seqExpr{
					pos: position{line: 38, col: 13, offset: 839},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 38, col: 13, offset: 839},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 38, col: 15, offset: 841},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 38, col: 18, offset: 844},
								name: "ID",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 38, col: 21, offset: 847},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 38, col: 23, offset: 849},
							label: "path",
							expr: &ruleRefExpr{
								pos:  position{line: 38, col: 28, offset: 854},
								name: "PATH",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 38, col: 33, offset: 859},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 38, col: 35, offset: 861},
							label: "obj",
							expr: &zeroOrOneExpr{
								pos: position{line: 38, col: 39, offset: 865},
								expr: &ruleRefExpr{
									pos:  position{line: 38, col: 39, offset: 865},
									name: "Object",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 38, col: 47, offset: 873},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 42, col: 1, offset: 925},
			expr: &actionExpr{
				pos: position{line: 42, col: 10, offset: 934},
				run: (*parser).callonValue1,
				expr: &labeledExpr{
					pos:   position{line: 42, col: 10, offset: 934},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 42, col: 16, offset: 940},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 42, col: 16, offset: 940},
								name: "Boolean",
							},
							&ruleRefExpr{
								pos:  position{line: 42, col: 26, offset: 950},
								name: "TypeDecl",
							},
							&ruleRefExpr{
								pos:  position{line: 42, col: 37, offset: 961},
								name: "Object",
							},
							&ruleRefExpr{
								pos:  position{line: 42, col: 46, offset: 970},
								name: "Array",
							},
							&ruleRefExpr{
								pos:  position{line: 42, col: 54, offset: 978},
								name: "Number",
							},
							&ruleRefExpr{
								pos:  position{line: 42, col: 63, offset: 987},
								name: "Integer",
							},
							&ruleRefExpr{
								pos:  position{line: 42, col: 73, offset: 997},
								name: "String",
							},
							&ruleRefExpr{
								pos:  position{line: 42, col: 82, offset: 1006},
								name: "PATH",
							},
							&ruleRefExpr{
								pos:  position{line: 42, col: 89, offset: 1013},
								name: "Null",
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 46, col: 1, offset: 1043},
			expr: &actionExpr{
				pos: position{line: 46, col: 10, offset: 1052},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 46, col: 10, offset: 1052},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 46, col: 10, offset: 1052},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 13, offset: 1055},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 16, offset: 1058},
								name: "ID",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 19, offset: 1061},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 46, col: 21, offset: 1063},
							val:        ":",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 25, offset: 1067},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 27, offset: 1069},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 31, offset: 1073},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 37, offset: 1079},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 50, col: 1, offset: 1122},
			expr: &actionExpr{
				pos: position{line: 50, col: 11, offset: 1132},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 50, col: 11, offset: 1132},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 50, col: 11, offset: 1132},
							val:        "{",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 50, col: 15, offset: 1136},
							label: "fields",
							expr: &zeroOrMoreExpr{
								pos: position{line: 50, col: 22, offset: 1143},
								expr: &ruleRefExpr{
									pos:  position{line: 50, col: 24, offset: 1145},
									name: "Field",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 33, offset: 1154},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 50, col: 36, offset: 1157},
							val:        "}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Elem",
			pos:  position{line: 54, col: 1, offset: 1201},
			expr: &actionExpr{
				pos: position{line: 54, col: 9, offset: 1209},
				run: (*parser).callonElem1,
				expr: &seqExpr{
					pos: position{line: 54, col: 9, offset: 1209},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 54, col: 9, offset: 1209},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 54, col: 12, offset: 1212},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 16, offset: 1216},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 22, offset: 1222},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 54, col: 24, offset: 1224},
							val:        ",",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 54, col: 28, offset: 1228},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 58, col: 1, offset: 1253},
			expr: &actionExpr{
				pos: position{line: 58, col: 10, offset: 1262},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 58, col: 10, offset: 1262},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 58, col: 10, offset: 1262},
							val:        "[",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 58, col: 14, offset: 1266},
							label: "elems",
							expr: &zeroOrMoreExpr{
								pos: position{line: 58, col: 20, offset: 1272},
								expr: &ruleRefExpr{
									pos:  position{line: 58, col: 22, offset: 1274},
									name: "Elem",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 58, col: 30, offset: 1282},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 58, col: 33, offset: 1285},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 62, col: 1, offset: 1327},
			expr: &actionExpr{
				pos: position{line: 62, col: 11, offset: 1337},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 62, col: 11, offset: 1337},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 62, col: 11, offset: 1337},
							expr: &litMatcher{
								pos:        position{line: 62, col: 11, offset: 1337},
								val:        "-",
								ignoreCase: false,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 62, col: 16, offset: 1342},
							name: "Integer",
						},
						&litMatcher{
							pos:        position{line: 62, col: 24, offset: 1350},
							val:        ".",
							ignoreCase: false,
						},
						&oneOrMoreExpr{
							pos: position{line: 62, col: 28, offset: 1354},
							expr: &ruleRefExpr{
								pos:  position{line: 62, col: 28, offset: 1354},
								name: "DecimalDigit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 62, col: 42, offset: 1368},
							expr: &ruleRefExpr{
								pos:  position{line: 62, col: 42, offset: 1368},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 66, col: 1, offset: 1410},
			expr: &choiceExpr{
				pos: position{line: 66, col: 12, offset: 1421},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 66, col: 12, offset: 1421},
						val:        "0",
						ignoreCase: false,
					},
					&actionExpr{
						pos: position{line: 66, col: 18, offset: 1427},
						run: (*parser).callonInteger3,
						expr: &seqExpr{
							pos: position{line: 66, col: 18, offset: 1427},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 66, col: 18, offset: 1427},
									name: "NonZeroDecimalDigit",
								},
								&zeroOrMoreExpr{
									pos: position{line: 66, col: 38, offset: 1447},
									expr: &ruleRefExpr{
										pos:  position{line: 66, col: 38, offset: 1447},
										name: "DecimalDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 70, col: 1, offset: 1494},
			expr: &seqExpr{
				pos: position{line: 70, col: 13, offset: 1506},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 70, col: 13, offset: 1506},
						val:        "e",
						ignoreCase: true,
					},
					&zeroOrOneExpr{
						pos: position{line: 70, col: 18, offset: 1511},
						expr: &charClassMatcher{
							pos:        position{line: 70, col: 18, offset: 1511},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 70, col: 24, offset: 1517},
						expr: &ruleRefExpr{
							pos:  position{line: 70, col: 24, offset: 1517},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 72, col: 1, offset: 1532},
			expr: &actionExpr{
				pos: position{line: 72, col: 11, offset: 1542},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 72, col: 11, offset: 1542},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 72, col: 11, offset: 1542},
							val:        "\"",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 72, col: 15, offset: 1546},
							expr: &choiceExpr{
								pos: position{line: 72, col: 17, offset: 1548},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 72, col: 17, offset: 1548},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 72, col: 17, offset: 1548},
												expr: &ruleRefExpr{
													pos:  position{line: 72, col: 18, offset: 1549},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 72, col: 30, offset: 1561,
											},
										},
									},
									&seqExpr{
										pos: position{line: 72, col: 34, offset: 1565},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 72, col: 34, offset: 1565},
												val:        "\\",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 72, col: 39, offset: 1570},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 72, col: 57, offset: 1588},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "AlphaNumericExtra",
			pos:  position{line: 76, col: 1, offset: 1624},
			expr: &choiceExpr{
				pos: position{line: 76, col: 22, offset: 1645},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 76, col: 22, offset: 1645},
						name: "Alphabetic",
					},
					&ruleRefExpr{
						pos:  position{line: 76, col: 35, offset: 1658},
						name: "DecimalDigit",
					},
					&litMatcher{
						pos:        position{line: 76, col: 50, offset: 1673},
						val:        "-",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 76, col: 56, offset: 1679},
						val:        "_",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "AlphaNumeric",
			pos:  position{line: 78, col: 1, offset: 1684},
			expr: &choiceExpr{
				pos: position{line: 78, col: 17, offset: 1700},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 78, col: 17, offset: 1700},
						name: "Alphabetic",
					},
					&ruleRefExpr{
						pos:  position{line: 78, col: 30, offset: 1713},
						name: "DecimalDigit",
					},
				},
			},
		},
		{
			name: "Alphabetic",
			pos:  position{line: 80, col: 1, offset: 1727},
			expr: &charClassMatcher{
				pos:        position{line: 80, col: 15, offset: 1741},
				val:        "[a-zA-Z]",
				ranges:     []rune{'a', 'z', 'A', 'Z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 82, col: 1, offset: 1751},
			expr: &charClassMatcher{
				pos:        position{line: 82, col: 16, offset: 1766},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 84, col: 1, offset: 1782},
			expr: &choiceExpr{
				pos: position{line: 84, col: 19, offset: 1800},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 84, col: 19, offset: 1800},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 84, col: 38, offset: 1819},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 86, col: 1, offset: 1834},
			expr: &charClassMatcher{
				pos:        position{line: 86, col: 21, offset: 1854},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 88, col: 1, offset: 1867},
			expr: &seqExpr{
				pos: position{line: 88, col: 18, offset: 1884},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 88, col: 18, offset: 1884},
						val:        "u",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 88, col: 22, offset: 1888},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 88, col: 31, offset: 1897},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 88, col: 40, offset: 1906},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 88, col: 49, offset: 1915},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 90, col: 1, offset: 1925},
			expr: &charClassMatcher{
				pos:        position{line: 90, col: 17, offset: 1941},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 92, col: 1, offset: 1948},
			expr: &charClassMatcher{
				pos:        position{line: 92, col: 24, offset: 1971},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 94, col: 1, offset: 1978},
			expr: &charClassMatcher{
				pos:        position{line: 94, col: 13, offset: 1990},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Boolean",
			pos:  position{line: 96, col: 1, offset: 2001},
			expr: &choiceExpr{
				pos: position{line: 96, col: 12, offset: 2012},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 96, col: 12, offset: 2012},
						run: (*parser).callonBoolean2,
						expr: &litMatcher{
							pos:        position{line: 96, col: 12, offset: 2012},
							val:        "true",
							ignoreCase: false,
						},
					},
					&actionExpr{
						pos: position{line: 96, col: 63, offset: 2063},
						run: (*parser).callonBoolean4,
						expr: &litMatcher{
							pos:        position{line: 96, col: 63, offset: 2063},
							val:        "false",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 100, col: 1, offset: 2146},
			expr: &actionExpr{
				pos: position{line: 100, col: 9, offset: 2154},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 100, col: 9, offset: 2154},
					val:        "null",
					ignoreCase: false,
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 102, col: 1, offset: 2182},
			expr: &zeroOrMoreExpr{
				pos: position{line: 102, col: 7, offset: 2188},
				expr: &choiceExpr{
					pos: position{line: 102, col: 9, offset: 2190},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 102, col: 9, offset: 2190},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 102, col: 22, offset: 2203},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 102, col: 28, offset: 2209},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 103, col: 1, offset: 2220},
			expr: &zeroOrMoreExpr{
				pos: position{line: 103, col: 6, offset: 2225},
				expr: &choiceExpr{
					pos: position{line: 103, col: 8, offset: 2227},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 103, col: 8, offset: 2227},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 103, col: 21, offset: 2240},
							name: "MultiLineCommentNoLineTerminator",
						},
					},
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 105, col: 1, offset: 2277},
			expr: &charClassMatcher{
				pos:        position{line: 105, col: 15, offset: 2291},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 106, col: 1, offset: 2299},
			expr: &litMatcher{
				pos:        position{line: 106, col: 8, offset: 2306},
				val:        "\n",
				ignoreCase: false,
			},
		},
		{
			name: "EOS",
			pos:  position{line: 107, col: 1, offset: 2311},
			expr: &choiceExpr{
				pos: position{line: 107, col: 8, offset: 2318},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 107, col: 8, offset: 2318},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 107, col: 8, offset: 2318},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 107, col: 11, offset: 2321},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
					&seqExpr{
						pos: position{line: 107, col: 17, offset: 2327},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 107, col: 17, offset: 2327},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 107, col: 19, offset: 2329},
								expr: &ruleRefExpr{
									pos:  position{line: 107, col: 19, offset: 2329},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 107, col: 38, offset: 2348},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 107, col: 44, offset: 2354},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 107, col: 44, offset: 2354},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 107, col: 47, offset: 2357},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 109, col: 1, offset: 2362},
			expr: &notExpr{
				pos: position{line: 109, col: 8, offset: 2369},
				expr: &anyMatcher{
					line: 109, col: 9, offset: 2370,
				},
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 111, col: 1, offset: 2373},
			expr: &anyMatcher{
				line: 111, col: 15, offset: 2387,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 112, col: 1, offset: 2389},
			expr: &choiceExpr{
				pos: position{line: 112, col: 12, offset: 2400},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 112, col: 12, offset: 2400},
						name: "MultiLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 112, col: 31, offset: 2419},
						name: "SingleLineComment",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 113, col: 1, offset: 2437},
			expr: &seqExpr{
				pos: position{line: 113, col: 21, offset: 2457},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 113, col: 21, offset: 2457},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 113, col: 26, offset: 2462},
						expr: &seqExpr{
							pos: position{line: 113, col: 28, offset: 2464},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 113, col: 28, offset: 2464},
									expr: &litMatcher{
										pos:        position{line: 113, col: 29, offset: 2465},
										val:        "*/",
										ignoreCase: false,
									},
								},
								&ruleRefExpr{
									pos:  position{line: 113, col: 34, offset: 2470},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 113, col: 48, offset: 2484},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			pos:  position{line: 114, col: 1, offset: 2489},
			expr: &seqExpr{
				pos: position{line: 114, col: 37, offset: 2525},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 114, col: 37, offset: 2525},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 114, col: 42, offset: 2530},
						expr: &seqExpr{
							pos: position{line: 114, col: 44, offset: 2532},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 114, col: 44, offset: 2532},
									expr: &choiceExpr{
										pos: position{line: 114, col: 47, offset: 2535},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 114, col: 47, offset: 2535},
												val:        "*/",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 114, col: 54, offset: 2542},
												name: "EOL",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 114, col: 60, offset: 2548},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 114, col: 74, offset: 2562},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 115, col: 1, offset: 2567},
			expr: &seqExpr{
				pos: position{line: 115, col: 22, offset: 2588},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 115, col: 22, offset: 2588},
						val:        "//",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 115, col: 27, offset: 2593},
						expr: &seqExpr{
							pos: position{line: 115, col: 29, offset: 2595},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 115, col: 29, offset: 2595},
									expr: &ruleRefExpr{
										pos:  position{line: 115, col: 30, offset: 2596},
										name: "EOL",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 115, col: 34, offset: 2600},
									name: "SourceChar",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DEF",
			pos:  position{line: 117, col: 1, offset: 2615},
			expr: &litMatcher{
				pos:        position{line: 117, col: 8, offset: 2622},
				val:        "def",
				ignoreCase: false,
			},
		},
		{
			name: "PACKAGE",
			pos:  position{line: 118, col: 1, offset: 2628},
			expr: &litMatcher{
				pos:        position{line: 118, col: 12, offset: 2639},
				val:        "package",
				ignoreCase: false,
			},
		},
		{
			name: "IMPORT",
			pos:  position{line: 119, col: 1, offset: 2649},
			expr: &litMatcher{
				pos:        position{line: 119, col: 11, offset: 2659},
				val:        "import",
				ignoreCase: false,
			},
		},
		{
			name: "PATH",
			pos:  position{line: 121, col: 1, offset: 2669},
			expr: &actionExpr{
				pos: position{line: 121, col: 9, offset: 2677},
				run: (*parser).callonPATH1,
				expr: &labeledExpr{
					pos:   position{line: 121, col: 9, offset: 2677},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 121, col: 15, offset: 2683},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 121, col: 15, offset: 2683},
								name: "ID",
							},
							&zeroOrMoreExpr{
								pos: position{line: 121, col: 18, offset: 2686},
								expr: &seqExpr{
									pos: position{line: 121, col: 20, offset: 2688},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 121, col: 20, offset: 2688},
											val:        ".",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 121, col: 24, offset: 2692},
											name: "ID",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ID",
			pos:  position{line: 125, col: 1, offset: 2735},
			expr: &actionExpr{
				pos: position{line: 125, col: 7, offset: 2741},
				run: (*parser).callonID1,
				expr: &labeledExpr{
					pos:   position{line: 125, col: 7, offset: 2741},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 125, col: 13, offset: 2747},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 125, col: 13, offset: 2747},
								name: "AlphaNumeric",
							},
							&zeroOrMoreExpr{
								pos: position{line: 125, col: 26, offset: 2760},
								expr: &ruleRefExpr{
									pos:  position{line: 125, col: 26, offset: 2760},
									name: "AlphaNumericExtra",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NAME",
			pos:  position{line: 129, col: 1, offset: 2814},
			expr: &actionExpr{
				pos: position{line: 129, col: 9, offset: 2822},
				run: (*parser).callonNAME1,
				expr: &labeledExpr{
					pos:   position{line: 129, col: 9, offset: 2822},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 129, col: 15, offset: 2828},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 129, col: 15, offset: 2828},
								name: "Alphabetic",
							},
							&zeroOrMoreExpr{
								pos: position{line: 129, col: 26, offset: 2839},
								expr: &ruleRefExpr{
									pos:  position{line: 129, col: 26, offset: 2839},
									name: "AlphaNumeric",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Token",
			pos:  position{line: 133, col: 1, offset: 2890},
			expr: &actionExpr{
				pos: position{line: 133, col: 10, offset: 2899},
				run: (*parser).callonToken1,
				expr: &labeledExpr{
					pos:   position{line: 133, col: 10, offset: 2899},
					label: "val",
					expr: &seqExpr{
						pos: position{line: 133, col: 16, offset: 2905},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 133, col: 16, offset: 2905},
								name: "Alphabetic",
							},
							&zeroOrMoreExpr{
								pos: position{line: 133, col: 27, offset: 2916},
								expr: &ruleRefExpr{
									pos:  position{line: 133, col: 27, offset: 2916},
									name: "AlphaNumeric",
								},
							},
						},
					},
				},
			},
		},
	},
}

func (c *current) onHOF1(pkg, imports, defs interface{}) (interface{}, error) {
	return FileCallback(c, pkg, imports, defs)
}

func (p *parser) callonHOF1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHOF1(stack["pkg"], stack["imports"], stack["defs"])
}

func (c *current) onPackageDecl1(name interface{}) (interface{}, error) {
	return PackageDeclCallback(c, name)
}

func (p *parser) callonPackageDecl1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPackageDecl1(stack["name"])
}

func (c *current) onImports1(imports interface{}) (interface{}, error) {
	return ImportsCallback(c, imports)
}

func (p *parser) callonImports1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onImports1(stack["imports"])
}

func (c *current) onImport1(name, path interface{}) (interface{}, error) {
	return ImportCallback(c, name, path)
}

func (p *parser) callonImport1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onImport1(stack["name"], stack["path"])
}

func (c *current) onDefinitions1(defs interface{}) (interface{}, error) {
	return DefinitionsCallback(c, defs)
}

func (p *parser) callonDefinitions1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefinitions1(stack["defs"])
}

func (c *current) onDefinition1(name, path, body interface{}) (interface{}, error) {
	return DefinitionCallback(c, name, path, body)
}

func (p *parser) callonDefinition1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefinition1(stack["name"], stack["path"], stack["body"])
}

func (c *current) onDefnBody1(defs interface{}) (interface{}, error) {
	return DefinitionBodyCallback(c, defs)
}

func (p *parser) callonDefnBody1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefnBody1(stack["defs"])
}

func (c *current) onDefnField1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonDefnField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefnField1(stack["val"])
}

func (c *current) onTypeDecl1(id, path, obj interface{}) (interface{}, error) {
	return TypeDeclCallback(c, id, path, obj)
}

func (p *parser) callonTypeDecl1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeDecl1(stack["id"], stack["path"], stack["obj"])
}

func (c *current) onValue1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onField1(id, val interface{}) (interface{}, error) {
	return FieldCallback(c, id, val)
}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["id"], stack["val"])
}

func (c *current) onObject1(fields interface{}) (interface{}, error) {
	return ObjectCallback(c, fields)
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["fields"])
}

func (c *current) onElem1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonElem1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onElem1(stack["val"])
}

func (c *current) onArray1(elems interface{}) (interface{}, error) {
	return ArrayCallback(c, elems)
}

func (p *parser) callonArray1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray1(stack["elems"])
}

func (c *current) onNumber1() (interface{}, error) {
	return NumberCallback(c)
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onInteger3() (interface{}, error) {
	return IntegerCallback(c)
}

func (p *parser) callonInteger3() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger3()
}

func (c *current) onString1() (interface{}, error) {
	return StringCallback(c)
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onBoolean2() (interface{}, error) {
	return &ast.Bool{Value: true}, nil
}

func (p *parser) callonBoolean2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean2()
}

func (c *current) onBoolean4() (interface{}, error) {
	return &ast.Bool{Value: false}, nil
}

func (p *parser) callonBoolean4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean4()
}

func (c *current) onNull1() (interface{}, error) {
	return nil, nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onPATH1(val interface{}) (interface{}, error) {
	return PathCallback(c, val)
}

func (p *parser) callonPATH1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPATH1(stack["val"])
}

func (c *current) onID1(val interface{}) (interface{}, error) {
	return IdCallback(c, val)
}

func (p *parser) callonID1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onID1(stack["val"])
}

func (c *current) onNAME1(val interface{}) (interface{}, error) {
	return NameCallback(c, val)
}

func (p *parser) callonNAME1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNAME1(stack["val"])
}

func (c *current) onToken1(val interface{}) (interface{}, error) {
	return TokenCallback(c, val)
}

func (p *parser) callonToken1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onToken1(stack["val"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
