FROM node:18-alpine3.16

WORKDIR /app

ENV PATH="/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin"

# install extra tools
RUN apk update && apk add \
	ruby-dev

RUN gem install \
	bundler \
	prettier_print \
	syntax_tree \
	syntax_tree-haml

# install direct dependencies
COPY package.json yarn.lock /app/
RUN yarn install

# our server code
COPY prettier.js .

# runtime settings
EXPOSE 3000
CMD ["node", "prettier.js"]
