/*
This package manages the #hof: _ configuration
and the various @<hof>() attributes
*/
package hof

// [[ hof2veg ]]
// HMM, it would be great to make this package extensible, for anyone else that wants to use the same metadata &| cli system on top of CUE
// thinking about that today, it seems like Go, generics in particular, has come a long way. We should look into this during the rewrite, it would make our own system way more modular.

// #hof: ...
type Hof struct {
	// A unique ID as @id(string) generated by hof if not set
	// setting this helps with deduplication and caching
	// when managing the "copy-on-write"-ish-ness in Go/CUE/Dagger
	ID string `json:"id"`

	// label from containing value in CUE
	Label string

	// path to containing value in CUE
	Path string

	// Semantic #hof schema version for future backwards compatibility, not used today
	APIVersion string

	// #hof: metadata: ...
	Metadata Metadata

	// #hof: memo: "<id>"", memoization hinting
	Memo string

	// is this #hof associated with any @...
	AtMade bool

	// a "z" index for presentation
	Z int

	// #hof: <feature>: ...
	// @<feature>(<name>) can be shorthand with no-name implying label?
	Datamodel Datamodel
	Gen       Gen
	Flow      Flow
	Env       Env
	Agentic   Agentic

	// any extra config, set by users
	Extra map[string]any
}

// Common Metadata
type Metadata struct {
	// Given name for the value
	Name string `json:"name"`

	// Words for man or machine
	Description string `json:"description"`

	// arbitrary key=string data used by the system
	Labels map[string]string `json:"labels"`

	// arbitrary key=string data used by 3rd party
	//   key is reverse domain namespaced
	Annotations map[string]string `json:"annotations"`
}

// hof/datamodel configuration
type Datamodel struct {
	// Root for datamodel features
	// This acts as the entrypoint
	// the other fields determine behavior
	Root bool

	// index, pivot, level, hierachy, node?
	Node bool

	// Enable snapshots and history in .hof/dm/...
	History bool

	// create an Ordered<Label> list in parent data
	// where elements are from CUE iteration of fields
	Ordered bool

	// treat as a cue value
	// nesting stops here and the whole
	// value is tracked as a singular value
	// support incomplete values & schemas
	Cue bool

	// Semantic version for value
	Version string
}

// hof/gen configuration
// #hof: gen: "name"
// @gen(name)
type Gen struct {
	Root    bool
	Name    string
	Creator bool
}

/*
	  hof/flow configuration
	  this has more shorthands
		@flow() | @flow(name)
		@task(op) | @task(op,name)
*/
type Flow struct {
	Root bool
	Name string
	Task string

	// middleware related
	Pool  Pool
	Print Print
}

/*
		hof/flow configuration
		@pool(<name>[,num])
	  @pool(name,3) // create pool of 3
	  @pool(name)   // take from pool
*/
type Pool struct {
	Name   string
	Number int

	Make bool
	Take bool
}

type Print struct {
	Level   int
	Before  bool
	Message string
	Path    string
}

// hof/env configuration
// #hof: env: "name"
// @env(extra)
type Env struct {
	Root  bool
	Name  string
	Kind  string
	Extra string
}

// hof/agent configuration
// #hof: agent: "name"
// @agent(extra)
type Agentic struct {
	Root  bool
	Name  string
	Kind  string
	Extra string
}
