package flags

var (
	RootLabelsPflag             []string
	RootConfigPflag             string
	RootSecretPflag             string
	RootContextFilePflag        string
	RootContextPflag            string
	RootGlobalPflag             bool
	RootLocalPflag              bool
	RootInputPflag              []string
	RootInputFormatPflag        string
	RootOutputPflag             []string
	RootOutputFormatPflag       string
	RootErrorPflag              []string
	RootErrorFormatPflag        string
	RootAccountPflag            string
	RootBillingPflag            string
	RootProjectPflag            string
	RootWorkspacePflag          string
	RootDatamodelDirPflag       string
	RootResourcesDirPflag       string
	RootRuntimesDirPflag        string
	RootPackagePflag            string
	RootErrorsPflag             bool
	RootIgnorePflag             bool
	RootSimplifyPflag           bool
	RootTracePflag              bool
	RootStrictPflag             bool
	RootVerbosePflag            string
	RootQuietPflag              bool
	RootImpersonateAccountPflag string
	RootTraceTokenPflag         string
	RootLogHTTPPflag            string
	RootRunUIPflag              bool
	RootRunTUIPflag             bool
)
