// Code generated by gocode.Generate; DO NOT EDIT.

package pkg2

import (
	"fmt"

	"github.com/hofstadter-io/hof/pkg/lang/encoding/gocode/gocodec"
	"github.com/hofstadter-io/hof/pkg/lang/hof"
)

var cuegenvalImportMe = cuegenMake("ImportMe", &ImportMe{})

// Validate validates x.
func (x *ImportMe) Validate() error {
	return cuegenCodec.Validate(cuegenvalImportMe, x)
}

var cuegenvalPickMe = cuegenMake("PickMe", nil)

// Validate validates x.
func (x PickMe) Validate() error {
	return cuegenCodec.Validate(cuegenvalPickMe, x)
}

var cuegenCodec, cuegenInstance = func() (*gocodec.Codec, *cue.Instance) {
	var r *cue.Runtime
	r = &cue.Runtime{}
	instances, err := r.Unmarshal(cuegenInstanceData)
	if err != nil {
		panic(err)
	}
	if len(instances) != 1 {
		panic("expected encoding of exactly one instance")
	}
	return gocodec.New(r, nil), instances[0]
}()

// cuegenMake is called in the init phase to initialize CUE values for
// validation functions.
func cuegenMake(name string, x interface{}) cue.Value {
	f, err := cuegenInstance.LookupField(name)
	if err != nil {
		panic(fmt.Errorf("could not find type %q in instance", name))
	}
	v := f.Value
	if x != nil {
		w, err := cuegenCodec.ExtractType(x)
		if err != nil {
			panic(err)
		}
		v = v.Unify(w)
	}
	return v
}

// Data size: 292 bytes.
var cuegenInstanceData = []byte("\x01\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xffD\x8f\xc1J\x031\x10\x86g\xb6+\xd8P\x05\x1f@X\xf6T\x0fn\xaa B\x11\xa1V\x04\x0fJ\xf1*\x1e\xa6\xd94\rm\x93\xd2L\x0f\"\x1e\xd4Z}1\x9f+\x92R\xf14\xcc7\xff7\xcc\xec\u016f\f\xb3\xf8\r\x18\xdf\x01\xce\xe3[\x03\xb1e]`rJ_\x13S\xe2\xd8\xc0\xfc\xc1{\xc6\f0\x1f\x10\x8f\xb1\x05\xb8sc\xa7:`\\\x03\xc0a\xfc\xcc\x10\xf7\x1f\x9f\xd4RW#;\u075ak\xc0\xb8\x02h\u01cf\x06\xe2\xee?_\x01f\x98\xdf\xd3L\xa7E\xf9\x06\n\x00\x88?\xe9\x10D\xec\x1b\xcb\xe3\xe5\xb0R~&\xc7~\x14\x98j\u058bc\xebS'\xe7\x13#\xa7\xe4\x8c\xd4N\xf9\xda:#\x8dW\xbe\u0592u\xe0\x9a\x98R\xe2\x14\x11\x0fR\x95\u007f\xdfTj\xa9\x91\xe6\xa4&dt\x91FB\xd8\xd9\xdc/\xb8(\x03/\xac3\xa1\x14\xe2vC\xeet\xb7x\x11\xcd^\xb7\xb88\xe9tD\xf3\xaa[l#U\xdf;&\xebB\xcf=\xb7K\x1a\xaa\xf2H\xbc\x8a\x81U\x93\xe4\\\x9e\t\x80\xdf\x00\x00\x00\xff\xff\xf0\x8c\xff2T\x01\x00\x00")
