name: dagger
"on":
  - push
env:
  HOF_TELEMETRY_DISABLED: "1"
  HOF_FMT_VERSION: v0.6.8
jobs:
  inception:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-inception-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Vars
        id: vars
        run: |-
          SHA=${GITHUB_SHA::8}
          TAG=$(git tag --points-at HEAD)
          echo "HOF_FMT_VERSION=${TAG}" >> $GITHUB_ENV
          if [ -z $TAG ]; then
          	TAG=${SHA}
          fi
          echo "HOF_SHA=${SHA}" >> $GITHUB_ENV
          echo "HOF_TAG=${TAG}" >> $GITHUB_ENV
      - name: Fetch Go deps
        run: go mod download
      - name: Test Compatibility
        run: |-
          docker version
          docker info
          docker context ls
          go run test/docker/main.go
      - name: dagger-in-dagger
        run: go run ./test/dagger/main/dagger-in-dagger.go
      - name: dockerd-in-dagger
        run: go run ./test/dagger/main/dockerd-in-dagger.go
    strategy: {}
    services: {}
  hof:
    environment: hof mod testing
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-hof-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x
      - uses: actions/cache@v3
        with:
          path: |-
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-dagger-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-dagger-
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Vars
        id: vars
        run: |-
          SHA=${GITHUB_SHA::8}
          TAG=$(git tag --points-at HEAD)
          echo "HOF_FMT_VERSION=${TAG}" >> $GITHUB_ENV
          if [ -z $TAG ]; then
          	TAG=${SHA}
          fi
          echo "HOF_SHA=${SHA}" >> $GITHUB_ENV
          echo "HOF_TAG=${TAG}" >> $GITHUB_ENV
      - name: Fetch Go deps
        run: go mod download
      - name: Test Compatibility
        run: |-
          docker version
          docker info
          docker context ls
          go run test/docker/main.go
      - name: hof-in-dagger
        run: go run ./test/dagger/main/hof.go
        env:
          GITHUB_TOKEN: ${{secrets.HOF_HOMEBREW_PAT}}
          GITLAB_TOKEN: ${{secrets.GITLAB_TOKEN}}
          BITBUCKET_USERNAME: hofstadter
          BITBUCKET_PASSWORD: ${{secrets.BITBUCKET_TOKEN}}
    strategy: {}
    services: {}
